### ISSUE TITLE
Is there a way to get name of current state?

### ISSUE THREAD

**Issue by aubergine10** [kikito/stateful.lua#2]
The closest thing I can see is `getStateStackDebugInfo()` and look at what's in `#` (last) element of the returned table.

Would be nice if there was a `:getState()` method that returns the current state (or nil if no state). Another useful method would be `:isState(nameOrState)` which would return `true` if specified `name` or `state` is the currently active state?

One last question: Is it possible to prevent stacking of states (ie. only one state - or no states - can be in the stack at any given time)?

**Comment by kikito** [comment]
Hi there,

I apologize for not answering to this sooner. It arrived in a very ... "interesting" time in my life, while I was changing jobs.

The fact that Stateful does not provide a way to "get the current state name" or a "isInState" function was not an oversight - it is by design.

The problem with the `:getState` function is that it encourages doing non-stateful stuff like the following:

```lua
function Enemy:talk()
  if self:getState() == 'Scared' then
    print("Aaaaah!")
  elseif self:getState() == 'Drunk' then
    print("Burp")
  else -- no state, and rest of the states
    print("Du-di-du")
  end
end
```

This if-else-if-else construction is *precisely* what `Stateful` is set up to *not* have. Instead, what you should do in this case is split all that behavior into different smaller functions, each one on its own state:

```lua
function Scared:talk()
  print("Aaaaah!")
end

function Drunk:talk()
  print("Burp")
end

function Enemy:talk() -- the default one, when not in a state
  print("Du-di-du")
end
```

The same happens with `:isState`: it encourages using `ifs` instead of adding new functions, so I didn't include it.

That said: you can totally create those functions if you want. Like so:

```lua
function Scared:getState()
  return 'Scared'
end
function Scared:isInState(stateName)
  return stateName == 'Scared'
end
```
... And so on - returning `nil` and `false` in the default, non-stateful methods.

My hope is that when you do that you realize that there is a lot of duplicated code and that signals that maybe something could be improved.

The reason I left getStateStackDebugInfo() is because I recognized that there is usually a need to debug in which it is useful to print the state name on the screen, but I didn't want people to use it for making "ifs".

>  Is it possible to prevent stacking of states (ie. only one state - or no states - can be in the stack at any given time)?

`gotoState` always "resets the stack" to one level (even if there are states on the stack). If you always use `gotoState` and never use `pushState` or `popState` you should not have stacked states.

I don't know if this answer your questions - for now I will close down this issue, feel free to answer / reopen if you want.

Thanks for using my library!
